// app/layout.tsx
import { Metadata } from "next";
import localFont from "next/font/local";
import Navbar from "../components/navbar/page"; // Import Navbar component
import "./globals.css";
import FooterSection from "@/components/footer/footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-gradient-to-b from-gray-900 via-gray-800 to-black ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Add Navbar here */}
        <Navbar />

        {/* Add padding-top to ensure content is not hidden behind the fixed navbar */}
        <main className="">{children}</main>
      </body>
    </html>
  );
}
